### ISSUE TITLE
button map incorrect in 32u4 demo code

### ISSUE THREAD

**Issue by infrarosso78** [Industruino/democode#1]
The demo code for the 32u4 board contains in the readButtons function the code to read input from a single analog pin. Is that correct?

**Comment by tomtobback** [comment]
Yes that is correct, the A5 analog pin as shown in the pinout diagram e.g. https://static.industruino.com/downloads/diagrams/Industruino_INDIO_32u4_pinout_map_Feb'15_S.pdf and same for PROTO 32u4.

**Comment by infrarosso78** [comment]
Thanks a lot!
