### ISSUE TITLE
Enhancement: Adding a Thingspeak library for Industruino IND.I/O D21G

### ISSUE THREAD

**Issue by ExcitePrime** [Industruino/democode#3]
Hello, I would like to ask if you have ever tried to use the Thingspeak library for Industruino D21G in combination with your GSM module? Since the current Thingspeak library is supported for Arduino MKR GSM 1400 and both the MKR GSM 1400 and the D21G have the same SAMD21 chip, although the GSM modules are different (SARA-U201 for MKR GSM, SIM800H for the D21G)

**Comment by tomtobback** [comment]
hi, there are a lot of IoT frameworks out there, we provides examples for a few of them. Usually it is quite easy to implement. From what i can see in the Thingspeak typical example, it would just be a matter of setting up the client in the Industruino code (Ethernet or GSM) and then passing that into ThingSpeak.begin(client);
